### PR TITLE
fix: update arrow to v12

### LINKED ISSUE #134: Build fails on 1.3.0 with arrow 11
When bumping to 1.3.0 go build started failing due to an [issue](https://github.com/apache/arrow/issues/34784) with arrow 11.
```
# github.com/apache/arrow/go/v11/internal/utils
/go/pkg/mod/github.com/apache/arrow/go/v11@v11.0.0-20221220213742-09453f9258f3/internal/utils/transpose_ints_def.go:76:4: undefined: TransposeInt8Int8
/go/pkg/mod/github.com/apache/arrow/go/v11@v11.0.0-20221220213742-09453f9258f3/internal/utils/transpose_ints_def.go:78:4: undefined: TransposeInt8Int16
/go/pkg/mod/github.com/apache/arrow/go/v11@v11.0.0-20221220213742-09453f9258f3/internal/utils/transpose_ints_def.go:80:4: undefined: TransposeInt8Int32
/go/pkg/mod/github.com/apache/arrow/go/v11@v11.0.0-20221220213742-09453f9258f3/internal/utils/transpose_ints_def.go:82:4: undefined: TransposeInt8Int64
/go/pkg/mod/github.com/apache/arrow/go/v11@v11.0.0-20221220213742-09453f9258f3/internal/utils/transpose_ints_def.go:84:4: undefined: TransposeInt8Uint8
/go/pkg/mod/github.com/apache/arrow/go/v11@v11.0.0-20221220213742-09453f9258f3/internal/utils/transpose_ints_def.go:86:4: undefined: TransposeInt8Uint16
/go/pkg/mod/github.com/apache/arrow/go/v11@v11.0.0-20221220213742-09453f9258f3/internal/utils/transpose_ints_def.go:88:4: undefined: TransposeInt8Uint32
/go/pkg/mod/github.com/apache/arrow/go/v11@v11.0.0-20221220213742-09453f9258f3/internal/utils/transpose_ints_def.go:90:4: undefined: TransposeInt8Uint64
/go/pkg/mod/github.com/apache/arrow/go/v11@v11.0.0-20221220213742-09453f9258f3/internal/utils/transpose_ints_def.go:95:4: undefined: TransposeInt16Int8
/go/pkg/mod/github.com/apache/arrow/go/v11@v11.0.0-20221220213742-09453f9258f3/internal/utils/transpose_ints_def.go:97:4: undefined: TransposeInt16Int16
/go/pkg/mod/github.com/apache/arrow/go/v11@v11.0.0-20221220213742-09453f9258f3/internal/utils/transpose_ints_def.go:97:4: too many errors
Error: running "go build -o databricks -ldflags -w -s -extldflags "-static"
```
Bumping arrow to 12 will fix it.

### PR DESCRIPTION
**Pull request by scottlepp**
Fixes #134

### CODE REVIEW

**Comment by scottlepp** [comment]
Hi @rcypher-databricks pretty easy/straightforward one here.  Can you take a look please?

**Review by rcypher-databricks — APPROVED** [review]
